# GENERATED — DO NOT EDIT.
# Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
# Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
# Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
# See generated/sdk-registry/README.md for the rules this data is fed to.

module Tork
  module Governance
    module Pii
      REGISTRY_VERSION = '1.2.0'
      CONTENT_HASH = 'cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26'

      # The keyword gate is ASYMMETRIC — see README.md, rule 3.
      KEYWORD_WINDOW_BEFORE = 60
      KEYWORD_WINDOW_AFTER = 40
      CONTEXT_WINDOW = 60
      LABEL_WINDOW = 60
      LABEL_REACH = 25

      NEAR_MISS_REDACTION = '[NATIONAL_ID_REDACTED]'
      NEAR_MISS_TYPE = 'national_id_near_miss'
      NEAR_MISS_KINDS = ['health_id', 'national_id', 'tax_id'].freeze

      TABLE_DELIMITERS = ["\t", "|", ";", ","].freeze
      TABLE_MAX_HEADER_LENGTH = 32
      TABLE_MAX_HEADER_WORDS = 4
      TABLE_MIN_ROWS = 3
      TABLE_MIN_COMMA_COLUMNS = 3

      LABELS = [
        'AADHAAR',
        'ABN',
        'ACN',
        'BVN',
        'CA_PASSPORT',
        'CA_PHONE',
        'CA_POSTAL',
        'CNIC',
        'CNPJ',
        'CODICE_FISCALE',
        'CPF',
        'EMIRATES_ID',
        'GHANA_CARD',
        'IFSC',
        'ITIN',
        'KRA_PIN',
        'MEDICARE',
        'MYKAD',
        'MY_NUMBER',
        'NATIONAL_ID',
        'NHS',
        'NIK',
        'NIN',
        'NINO',
        'NRIC',
        'PAN',
        'PASSPORT',
        'PHONE',
        'PINCODE',
        'PO_BOX',
        'RESIDENT_ID',
        'RFC',
        'RRN',
        'SIN',
        'SORT_CODE',
        'TAN',
        'TAX_ID',
        'TFN',
        'UK_POSTCODE',
        'ZA_ID',
      ].freeze

      REFERENCE_LABELS = [
        'order',
        'invoice',
        'purchase order',
        'po no',
        'po number',
        'job number',
        'job no',
        'booking',
        'tracking',
        'consignment',
        'waybill',
        'airway bill',
        'awb',
        'docket',
        'quote',
        'quotation',
        'ticket',
        'receipt',
        'serial number',
        'asset tag',
        'part number',
        'stock code',
        'batch',
        'shipment',
        'dispatch note',
        'delivery note',
        'work order',
        'contract number',
        'policy number',
        'meter number',
        'case id',
        'bestelling',
        'bestelnommer',
        'faktuur',
        'kwotasie',
        'commande',
        'facture',
        'devis',
        'bon de livraison',
        'expédition',
        'expedition',
        'pedido',
        'fatura',
        'factura',
        'orçamento',
        'orcamento',
        'presupuesto',
        'remito',
        'pesanan',
        'nombor pesanan',
        'invois',
        'sebut harga',
        'penghantaran',
        'resit',
        'आदेश',
        'क्रय आदेश',
        'चालान',
        'कोटेशन',
        'रसीद',
        'آرڈر',
        'انوائس',
        'رسید',
        'کوٹیشن',
        'ترسیل',
        'طلب',
        'أمر شراء',
        'فاتورة',
        'عرض سعر',
        'إيصال',
        'شحنة',
        'بوليصة',
        '注文',
        '注文番号',
        '発注',
        '発注番号',
        '請求書',
        '請求番号',
        '伝票',
        '伝票番号',
        '見積',
        '見積番号',
        '管理番号',
        '在庫番号',
        '受注',
        '出荷',
        '订单',
        '訂單',
        '订单编号',
        '訂單編號',
        '发票',
        '發票',
        '采购',
        '採購',
        '报价',
        '報價',
        '运单',
        '運單',
        '物料编号',
        '物料編號',
        '库存',
        '庫存',
        '주문',
        '주문번호',
        '구매주문',
        '송장',
        '견적',
        '견적서',
        '운송장',
        '자재번호',
        '재고번호',
        'ใบสั่งซื้อ',
        'เลขที่ใบสั่งซื้อ',
        'ใบแจ้งหนี้',
        'ใบเสนอราคา',
        'ใบส่งของ',
        'รหัสพัสดุ',
        'ใบงาน',
      ].freeze

      GENERIC_ID_KEYWORDS = [
        'national id',
        'national identity',
        'national identification',
        'national number',
        'national code',
        'identity number',
        'identification number',
        'id number',
        'citizen id',
        'citizen number',
        'resident id',
        'resident number',
        'civil id',
        'civil number',
        'civil registration',
        'personal number',
        'personal identity',
        'personal code',
        'personal id',
        'tax identification',
        'tax reference',
        'taxpayer number',
        'taxpayer id',
      ].freeze

      LOCAL_ID_KEYWORDS = [
        'cedula',
        'cédula',
        'iqama',
        'nadra',
        'cnic',
        'aadhaar',
        'voen',
        'vöen',
        'егн',
        'oib',
        'cpr-nummer',
        'cpr nummer',
        'kennitala',
        'personnummer',
        'adoazonosito',
        'adóazonosító',
        'szemelyi azonosito',
        'személyi azonosító',
        'kimlik',
        'рнокпп',
        'nid number',
        'sars income tax',
      ].freeze

      COUNTRIES = [
        { code: 'AU', name: 'Australia', calling_code: '61', bloc: false, patterns: ['au_tfn', 'au_abn', 'au_medicare', 'au_acn', 'au_phone_intl'] },
        { code: 'US', name: 'United States', calling_code: '1', bloc: false, patterns: ['us_itin', 'us_passport_alpha'] },
        { code: 'GB', name: 'United Kingdom', calling_code: '44', bloc: false, patterns: ['uk_phone_full', 'uk_sort_code', 'uk_nino', 'uk_nhs', 'uk_postcode'] },
        { code: 'EU', name: 'European Union', calling_code: '', bloc: true, patterns: ['de_tax_id'] },
        { code: 'AE', name: 'United Arab Emirates', calling_code: '971', bloc: false, patterns: ['emirates_id', 'uae_phone', 'uae_landline', 'po_box'] },
        { code: 'SA', name: 'Saudi Arabia', calling_code: '966', bloc: false, patterns: ['sa_national_id', 'sa_phone'] },
        { code: 'NG', name: 'Nigeria', calling_code: '234', bloc: false, patterns: ['ng_nin', 'ng_bvn', 'ng_phone'] },
        { code: 'IN', name: 'India', calling_code: '91', bloc: false, patterns: ['in_aadhaar', 'in_pan', 'in_phone', 'in_ifsc', 'in_pincode'] },
        { code: 'JP', name: 'Japan', calling_code: '81', bloc: false, patterns: ['jp_my_number', 'jp_phone_intl', 'jp_phone_national'] },
        { code: 'CN', name: 'China', calling_code: '86', bloc: false, patterns: ['cn_resident_id', 'cn_phone_intl', 'cn_phone_national'] },
        { code: 'KR', name: 'South Korea', calling_code: '82', bloc: false, patterns: ['kr_rrn', 'kr_phone_intl', 'kr_phone_national'] },
        { code: 'BR', name: 'Brazil', calling_code: '55', bloc: false, patterns: ['br_cpf', 'br_cnpj'] },
        { code: 'CA', name: 'Canada', calling_code: '1', bloc: false, patterns: ['ca_sin', 'ca_phone', 'ca_postal_code', 'ca_passport'] },
        { code: 'ZA', name: 'South Africa', calling_code: '27', bloc: false, patterns: ['za_id_number', 'za_phone'] },
        { code: 'GH', name: 'Ghana', calling_code: '233', bloc: false, patterns: ['gh_ghana_card'] },
        { code: 'IT', name: 'Italy', calling_code: '39', bloc: false, patterns: ['it_codice_fiscale'] },
        { code: 'KE', name: 'Kenya', calling_code: '254', bloc: false, patterns: ['ke_kra_pin'] },
        { code: 'MU', name: 'Mauritius', calling_code: '230', bloc: false, patterns: ['mu_tan'] },
        { code: 'MX', name: 'Mexico', calling_code: '52', bloc: false, patterns: ['mx_rfc'] },
        { code: 'MY', name: 'Malaysia', calling_code: '60', bloc: false, patterns: ['my_mykad'] },
        { code: 'PK', name: 'Pakistan', calling_code: '92', bloc: false, patterns: ['pk_cnic'] },
        { code: 'SG', name: 'Singapore', calling_code: '65', bloc: false, patterns: ['sg_nric'] },
        { code: 'TH', name: 'Thailand', calling_code: '66', bloc: false, patterns: ['th_national_id'] },
        { code: 'ID', name: 'Indonesia', calling_code: '62', bloc: false, patterns: ['id_nik'] },
      ].freeze

      PATTERNS = [
        {
          name: 'au_tfn',
          country: 'AU',
          kind: 'tax_id',
          regex: '\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b',
          redaction: '[TFN_REDACTED]',
          type: 'au_tfn',
          label: 'TFN',
          requires_keyword: true,
          always_on: true,
          keywords: ['tfn', 'tax file', 'tax number'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'au_tfn',
          checksum_required: true
        },
        {
          name: 'au_abn',
          country: 'AU',
          kind: 'company',
          regex: '\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b',
          redaction: '[ABN_REDACTED]',
          type: 'au_abn',
          label: 'ABN',
          requires_keyword: true,
          always_on: true,
          keywords: ['abn', 'business number', 'australian business'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'au_abn',
          checksum_required: true
        },
        {
          name: 'au_medicare',
          country: 'AU',
          kind: 'health_id',
          regex: '\\b\\d{4}[ \\t]?\\d{5}[ \\t]?\\d{1}\\b',
          redaction: '[MEDICARE_REDACTED]',
          type: 'au_medicare',
          label: 'MEDICARE',
          requires_keyword: true,
          always_on: true,
          keywords: ['medicare'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'au_medicare',
          checksum_required: false
        },
        {
          name: 'au_acn',
          country: 'AU',
          kind: 'company',
          regex: '\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b',
          redaction: '[ACN_REDACTED]',
          type: 'au_acn',
          label: 'ACN',
          requires_keyword: true,
          always_on: false,
          keywords: ['acn', 'company number', 'australian company'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'au_phone_intl',
          country: 'AU',
          kind: 'phone',
          regex: '\\+61[ \\t]?[2-478](?:[ \\t]?\\d){8}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'au_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'us_itin',
          country: 'US',
          kind: 'tax_id',
          regex: '\\b9\\d{2}-[7-9]\\d-\\d{4}\\b',
          redaction: '[ITIN_REDACTED]',
          type: 'us_itin',
          label: 'ITIN',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'us_passport_alpha',
          country: 'US',
          kind: 'passport',
          regex: '\\b[A-Z]\\d{8}\\b',
          redaction: '[PASSPORT_REDACTED]',
          type: 'us_passport',
          label: 'PASSPORT',
          requires_keyword: true,
          always_on: false,
          keywords: ['passport'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'uk_phone_full',
          country: 'GB',
          kind: 'phone',
          regex: '(?:\\+44[ \\t]?|\\b0)(?:7\\d{3}|\\d{2,4})[ \\t]?\\d{3,4}[ \\t]?\\d{3,4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'uk_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'uk_sort_code',
          country: 'GB',
          kind: 'bank',
          regex: '\\b\\d{2}-\\d{2}-\\d{2}\\b',
          redaction: '[SORT_CODE_REDACTED]',
          type: 'uk_sort_code',
          label: 'SORT_CODE',
          requires_keyword: true,
          always_on: false,
          keywords: ['sort code', 'sort-code', 'bank', 'account'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'uk_nino',
          country: 'GB',
          kind: 'national_id',
          regex: '\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b',
          redaction: '[NINO_REDACTED]',
          type: 'national_id',
          label: 'NINO',
          requires_keyword: true,
          always_on: false,
          keywords: ['national insurance', 'ni number', 'nino', 'ni:', 'insurance number'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'uk_nhs',
          country: 'GB',
          kind: 'health_id',
          regex: '\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[NHS_REDACTED]',
          type: 'health_id',
          label: 'NHS',
          requires_keyword: true,
          always_on: false,
          keywords: ['nhs', 'national health', 'nhs number', 'health service'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'uk_nhs',
          checksum_required: true
        },
        {
          name: 'uk_postcode',
          country: 'GB',
          kind: 'postcode',
          regex: '\\b[A-Z]{1,2}\\d[A-Z\\d]?[ \\t]?\\d[A-Z]{2}\\b',
          redaction: '[UK_POSTCODE_REDACTED]',
          type: 'postal_code',
          label: 'UK_POSTCODE',
          requires_keyword: true,
          always_on: false,
          keywords: ['postcode', 'post code', 'uk', 'united kingdom', 'britain', 'england', 'scotland', 'wales'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'de_tax_id',
          country: 'EU',
          kind: 'tax_id',
          regex: '\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b',
          redaction: '[TAX_ID_REDACTED]',
          type: 'de_tax_id',
          label: 'TAX_ID',
          requires_keyword: true,
          always_on: false,
          keywords: ['steuer', 'tax id', 'steuernummer', 'idnr', 'steueridentifikation'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'de_steuer_id',
          checksum_required: false
        },
        {
          name: 'emirates_id',
          country: 'AE',
          kind: 'national_id',
          regex: '\\b784-?\\d{4}-?\\d{7}-?\\d\\b',
          redaction: '[EMIRATES_ID_REDACTED]',
          type: 'emirates_id',
          label: 'EMIRATES_ID',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'ae_emirates_id',
          checksum_required: false
        },
        {
          name: 'uae_phone',
          country: 'AE',
          kind: 'phone',
          regex: '(?:\\+971[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'uae_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'uae_landline',
          country: 'AE',
          kind: 'phone',
          regex: '(?:\\+971[ \\t]?|\\b0)[2-4679][ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'uae_landline',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'po_box',
          country: 'AE',
          kind: 'postcode',
          regex: '\\b[Pp]\\.?[Oo]\\.?[ \\t]*[Bb]ox[ \\t]+\\d{3,6}\\b',
          redaction: '[PO_BOX_REDACTED]',
          type: 'po_box',
          label: 'PO_BOX',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'sa_national_id',
          country: 'SA',
          kind: 'national_id',
          regex: '\\b[12]\\d{9}\\b',
          redaction: '[NATIONAL_ID_REDACTED]',
          type: 'sa_national_id',
          label: 'NATIONAL_ID',
          requires_keyword: true,
          always_on: false,
          keywords: ['national id', 'iqama', 'national identification', 'resident id', 'saudi id'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'sa_national_id',
          checksum_required: false
        },
        {
          name: 'sa_phone',
          country: 'SA',
          kind: 'phone',
          regex: '(?:\\+966[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'sa_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'ng_nin',
          country: 'NG',
          kind: 'national_id',
          regex: '\\b\\d{11}\\b',
          redaction: '[NIN_REDACTED]',
          type: 'ng_nin',
          label: 'NIN',
          requires_keyword: true,
          always_on: false,
          keywords: ['nin', 'national id', 'national identification'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'ng_bvn',
          country: 'NG',
          kind: 'bank',
          regex: '\\b\\d{11}\\b',
          redaction: '[BVN_REDACTED]',
          type: 'ng_bvn',
          label: 'BVN',
          requires_keyword: true,
          always_on: false,
          keywords: ['bvn', 'bank verification'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'ng_phone',
          country: 'NG',
          kind: 'phone',
          regex: '(?:\\+234[ \\t]?|\\b0)[789]0[1-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'ng_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'in_aadhaar',
          country: 'IN',
          kind: 'national_id',
          regex: '\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b',
          redaction: '[AADHAAR_REDACTED]',
          type: 'in_aadhaar',
          label: 'AADHAAR',
          requires_keyword: true,
          always_on: false,
          keywords: ['aadhaar', 'aadhar', 'uid', 'unique identification', 'aadhaar number'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'verhoeff',
          checksum_required: true
        },
        {
          name: 'in_pan',
          country: 'IN',
          kind: 'tax_id',
          regex: '\\b[A-Z]{5}\\d{4}[A-Z]\\b',
          redaction: '[PAN_REDACTED]',
          type: 'in_pan',
          label: 'PAN',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'in_phone',
          country: 'IN',
          kind: 'phone',
          regex: '(?:\\+91[ \\t]?|\\b0|\\b)[6-9]\\d{4}[ \\t]?\\d{5}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'in_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'in_ifsc',
          country: 'IN',
          kind: 'bank',
          regex: '\\b[A-Z]{4}0[A-Z0-9]{6}\\b',
          redaction: '[IFSC_REDACTED]',
          type: 'in_ifsc',
          label: 'IFSC',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'in_pincode',
          country: 'IN',
          kind: 'postcode',
          regex: '\\b[1-9]\\d{5}\\b',
          redaction: '[PINCODE_REDACTED]',
          type: 'in_pincode',
          label: 'PINCODE',
          requires_keyword: true,
          always_on: false,
          keywords: ['pin code', 'pincode', 'postal code', 'zip', 'address'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'jp_my_number',
          country: 'JP',
          kind: 'national_id',
          regex: '\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b',
          redaction: '[MY_NUMBER_REDACTED]',
          type: 'jp_my_number',
          label: 'MY_NUMBER',
          requires_keyword: true,
          always_on: false,
          keywords: ['my number', 'individual number', 'マイナンバー'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'jp_my_number',
          checksum_required: true
        },
        {
          name: 'jp_phone_intl',
          country: 'JP',
          kind: 'phone',
          regex: '\\+81[ \\t-]?[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'jp_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'jp_phone_national',
          country: 'JP',
          kind: 'phone',
          regex: '\\b0[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'jp_phone',
          label: 'PHONE',
          requires_keyword: true,
          always_on: false,
          keywords: ['phone', 'telephone', 'tel', 'mobile', 'cell', 'fax', 'call', 'contact', 'whatsapp', 'hotline', 'landline', '電話', '電話番号', '携帯', '携帯番号', 'でんわ', '电话', '手机', '手機', '전화', '휴대', '휴대폰', '연락처'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'cn_resident_id',
          country: 'CN',
          kind: 'national_id',
          regex: '\\b\\d{6}(?:19|20)\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{3}[0-9Xx]\\b',
          redaction: '[RESIDENT_ID_REDACTED]',
          type: 'cn_resident_id',
          label: 'RESIDENT_ID',
          requires_keyword: true,
          always_on: false,
          keywords: ['resident id', 'resident identity', 'identity card', 'id card', 'national id', 'id number', 'id no', 'id:', 'id =', 'identity number', 'hukou', '身份证', '身份證', '居民身份证', '居民身份證'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'cn_resident_id',
          checksum_required: true
        },
        {
          name: 'cn_phone_intl',
          country: 'CN',
          kind: 'phone',
          regex: '\\+86[ \\t-]?1[3-9]\\d{9}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'cn_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'cn_phone_national',
          country: 'CN',
          kind: 'phone',
          regex: '\\b1[3-9]\\d{9}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'cn_phone',
          label: 'PHONE',
          requires_keyword: true,
          always_on: false,
          keywords: ['phone', 'telephone', 'tel', 'mobile', 'cell', 'fax', 'call', 'contact', 'whatsapp', 'hotline', 'landline', '電話', '電話番号', '携帯', '携帯番号', 'でんわ', '电话', '手机', '手機', '전화', '휴대', '휴대폰', '연락처'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'kr_rrn',
          country: 'KR',
          kind: 'national_id',
          regex: '\\b\\d{6}-?[1-4]\\d{6}\\b',
          redaction: '[RRN_REDACTED]',
          type: 'kr_rrn',
          label: 'RRN',
          requires_keyword: true,
          always_on: false,
          keywords: ['resident registration', 'resident number', 'registration number', 'rrn', 'jumin', 'juminbeonho', 'national id', 'id number', 'id no', 'id:', 'id =', 'identity number', '주민등록번호', '주민번호'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'kr_rrn',
          checksum_required: false
        },
        {
          name: 'kr_phone_intl',
          country: 'KR',
          kind: 'phone',
          regex: '\\+82[ \\t-]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'kr_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'kr_phone_national',
          country: 'KR',
          kind: 'phone',
          regex: '\\b01[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'kr_phone',
          label: 'PHONE',
          requires_keyword: true,
          always_on: false,
          keywords: ['phone', 'telephone', 'tel', 'mobile', 'cell', 'fax', 'call', 'contact', 'whatsapp', 'hotline', 'landline', '電話', '電話番号', '携帯', '携帯番号', 'でんわ', '电话', '手机', '手機', '전화', '휴대', '휴대폰', '연락처'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'br_cpf',
          country: 'BR',
          kind: 'national_id',
          regex: '\\b\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}\\b',
          redaction: '[CPF_REDACTED]',
          type: 'br_cpf',
          label: 'CPF',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: ['cpf', 'cadastro de pessoas', 'receita federal'],
          near_miss_fallback: true,
          checksum: 'br_cpf',
          checksum_required: true
        },
        {
          name: 'br_cnpj',
          country: 'BR',
          kind: 'company',
          regex: '\\b\\d{2}\\.?\\d{3}\\.?\\d{3}\\/?\\d{4}-?\\d{2}\\b',
          redaction: '[CNPJ_REDACTED]',
          type: 'br_cnpj',
          label: 'CNPJ',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'br_cnpj',
          checksum_required: true
        },
        {
          name: 'ca_sin',
          country: 'CA',
          kind: 'national_id',
          regex: '\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b',
          redaction: '[SIN_REDACTED]',
          type: 'ca_sin',
          label: 'SIN',
          requires_keyword: false,
          always_on: false,
          keywords: ['sin', 'social insurance', 'canada revenue', 'cra', 'employment insurance'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: 'ca_sin',
          checksum_required: false
        },
        {
          name: 'ca_phone',
          country: 'CA',
          kind: 'phone',
          regex: '\\b(\\+?1[-. \\t]?)?\\(?\\d{3}\\)?[-. \\t]\\d{3}[-. \\t]\\d{4}\\b',
          redaction: '[CA_PHONE_REDACTED]',
          type: 'phone',
          label: 'CA_PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: ['phone', 'mobile', 'cell', 'tel'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'ca_postal_code',
          country: 'CA',
          kind: 'postcode',
          regex: '\\b[A-Za-z]\\d[A-Za-z][ \\t-]?\\d[A-Za-z]\\d\\b',
          redaction: '[CA_POSTAL_REDACTED]',
          type: 'postal_code',
          label: 'CA_POSTAL',
          requires_keyword: false,
          always_on: false,
          keywords: ['postal', 'zip', 'post code', 'mailing'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'ca_passport',
          country: 'CA',
          kind: 'passport',
          regex: '\\b[A-Za-z]{2}\\d{6}\\b',
          redaction: '[CA_PASSPORT_REDACTED]',
          type: 'passport',
          label: 'CA_PASSPORT',
          requires_keyword: true,
          always_on: false,
          keywords: ['passport', 'travel document', 'citizenship'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'za_id_number',
          country: 'ZA',
          kind: 'national_id',
          regex: '\\b(\\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])(\\d{4})(0|1)(\\d{2})\\b',
          redaction: '[ZA_ID_REDACTED]',
          type: 'za_id_number',
          label: 'ZA_ID',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: ['sa id', 'rsa id', 'south african id', 'suid-afrikaanse id', 'id no', 'id-nommer', 'home affairs'],
          near_miss_fallback: true,
          checksum: 'za_id',
          checksum_required: true
        },
        {
          name: 'za_phone',
          country: 'ZA',
          kind: 'phone',
          regex: '(?:\\+27[ \\t]?|\\b0)[6-8]\\d[ \\t]?\\d{3}[ \\t]?\\d{4}\\b',
          redaction: '[PHONE_REDACTED]',
          type: 'za_phone',
          label: 'PHONE',
          requires_keyword: false,
          always_on: false,
          keywords: [],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'gh_ghana_card',
          country: 'GH',
          kind: 'national_id',
          regex: '\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b',
          redaction: '[GHANA_CARD_REDACTED]',
          type: 'gh_ghana_card',
          label: 'GHANA_CARD',
          requires_keyword: true,
          always_on: false,
          keywords: ['ghana card', 'ghanacard', 'ghana revenue', 'nia pin', 'personal id number', 'gra tin'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'it_codice_fiscale',
          country: 'IT',
          kind: 'tax_id',
          regex: '\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b',
          redaction: '[CODICE_FISCALE_REDACTED]',
          type: 'it_codice_fiscale',
          label: 'CODICE_FISCALE',
          requires_keyword: true,
          always_on: false,
          keywords: ['codice fiscale', 'cod. fisc', 'cod.fisc', 'c.f.', 'anagrafe tributaria', 'tessera sanitaria'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'it_codice_fiscale',
          checksum_required: true
        },
        {
          name: 'ke_kra_pin',
          country: 'KE',
          kind: 'tax_id',
          regex: '\\b[AP]\\d{9}[A-Z]\\b',
          redaction: '[KRA_PIN_REDACTED]',
          type: 'ke_kra_pin',
          label: 'KRA_PIN',
          requires_keyword: true,
          always_on: false,
          keywords: ['kra pin', 'kra', 'tax pin', 'itax', 'pin certificate', 'personal identification number'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'mu_tan',
          country: 'MU',
          kind: 'tax_id',
          regex: '\\b[123578]\\d{7}\\b',
          redaction: '[TAN_REDACTED]',
          type: 'mu_tan',
          label: 'TAN',
          requires_keyword: true,
          always_on: false,
          keywords: ['tax account number', 'mauritius revenue', 'tan ', 'tan:', 'tan no', 'tan number', 'mra tan'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'mx_rfc',
          country: 'MX',
          kind: 'tax_id',
          regex: '\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b',
          redaction: '[RFC_REDACTED]',
          type: 'mx_rfc',
          label: 'RFC',
          requires_keyword: true,
          always_on: false,
          keywords: ['rfc', 'homoclave', 'registro federal de contribuyentes', 'contribuyentes', 'constancia de situación fiscal'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'my_mykad',
          country: 'MY',
          kind: 'national_id',
          regex: '\\b\\d{6}-?\\d{2}-?\\d{4}\\b',
          redaction: '[MYKAD_REDACTED]',
          type: 'my_mykad',
          label: 'MYKAD',
          requires_keyword: true,
          always_on: false,
          keywords: ['mykad', 'my kad', 'kad pengenalan', 'no. kad pengenalan', 'nric', 'ic number', 'no. ic', 'mykid'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'pk_cnic',
          country: 'PK',
          kind: 'national_id',
          regex: '\\b\\d{5}-?\\d{7}-?\\d\\b',
          redaction: '[CNIC_REDACTED]',
          type: 'pk_cnic',
          label: 'CNIC',
          requires_keyword: true,
          always_on: false,
          keywords: ['cnic', 'nadra', 'nic number', 'identity card number', 'شناختی کارڈ', 'شناختی'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
        {
          name: 'sg_nric',
          country: 'SG',
          kind: 'national_id',
          regex: '\\b[STFGM]\\d{7}[A-Z]\\b',
          redaction: '[NRIC_REDACTED]',
          type: 'sg_nric',
          label: 'NRIC',
          requires_keyword: true,
          always_on: false,
          keywords: ['nric', 'fin number', 'fin no', 'fin:', 'identity card', 'identification number', 'cpf', 'singpass'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'sg_nric',
          checksum_required: true
        },
        {
          name: 'th_national_id',
          country: 'TH',
          kind: 'national_id',
          regex: '\\b\\d-?\\d{4}-?\\d{5}-?\\d{2}-?\\d\\b',
          redaction: '[NATIONAL_ID_REDACTED]',
          type: 'th_national_id',
          label: 'NATIONAL_ID',
          requires_keyword: true,
          always_on: false,
          keywords: ['national id', 'thai id', 'เลขประจำตัวประชาชน', 'บัตรประชาชน', 'เลขบัตร', 'promptpay'],
          whole_word_keywords: [],
          near_miss_keywords: [],
          near_miss_fallback: true,
          checksum: 'th_national_id',
          checksum_required: true
        },
        {
          name: 'id_nik',
          country: 'ID',
          kind: 'national_id',
          regex: '\\b\\d{16}\\b',
          redaction: '[NIK_REDACTED]',
          type: 'id_nik',
          label: 'NIK',
          requires_keyword: true,
          always_on: false,
          keywords: ['nomor induk kependudukan', 'kartu tanda penduduk', 'dukcapil'],
          whole_word_keywords: ['nik', 'e-ktp', 'ektp', 'ktp', 'npwp'],
          near_miss_keywords: [],
          near_miss_fallback: false,
          checksum: nil,
          checksum_required: false
        },
      ].freeze

      # In evaluation order. Stop at the first signal a country matches.
      SIGNALS = [
        {
          country: 'AU',
          regex: '\\b\\d{3}\\s\\d{3}\\s\\d{3}\\b',
          flags: '',
          keywords: ['tfn', 'tax file', 'medicare'],
          whole_word_keywords: [],
          activates: 'AU'
        },
        {
          country: 'AU',
          regex: '\\b\\d{4}\\s\\d{5}\\s\\d{1}\\b',
          flags: '',
          keywords: [],
          whole_word_keywords: [],
          activates: 'AU'
        },
        {
          country: 'AU',
          regex: '\\b(0[2-9]|\\+61)\\d{8,9}\\b',
          flags: '',
          keywords: ['au', 'australia', 'australian'],
          whole_word_keywords: [],
          activates: 'AU'
        },
        {
          country: 'GB',
          regex: '\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b',
          flags: 'i',
          keywords: ['national insurance', 'ni number', 'nino', 'ni:'],
          whole_word_keywords: [],
          activates: 'GB'
        },
        {
          country: 'GB',
          regex: '\\b[A-Z]{1,2}\\d{1,2}[ \\t]?\\d[A-Z]{2}\\b',
          flags: '',
          keywords: ['uk', 'united kingdom', 'britain', 'postcode'],
          whole_word_keywords: [],
          activates: 'GB'
        },
        {
          country: 'GB',
          regex: '\\b(\\+44|0044)\\d{10}\\b',
          flags: '',
          keywords: ['uk', 'united kingdom', 'britain'],
          whole_word_keywords: [],
          activates: 'GB'
        },
        {
          country: 'CA',
          regex: '\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b',
          flags: '',
          keywords: ['sin', 'social insurance', 'canada revenue', 'cra', 'employment insurance'],
          whole_word_keywords: [],
          activates: 'CA'
        },
        {
          country: 'CA',
          regex: '\\b[A-Za-z]\\d[A-Za-z][ \\t]?\\d[A-Za-z]\\d\\b',
          flags: '',
          keywords: ['canada', 'canadian', 'postal code', 'province'],
          whole_word_keywords: [],
          activates: 'CA'
        },
        {
          country: 'ZA',
          regex: '\\b\\d{13}\\b',
          flags: '',
          keywords: ['id number', 'identity number', 'south africa', 'sa id', 'rsa', 'popia', 'fica'],
          whole_word_keywords: [],
          activates: 'ZA'
        },
        {
          country: 'ZA',
          regex: '\\b(\\+27|0)[6-8]\\d{8}\\b',
          flags: '',
          keywords: ['south africa', 'za', 'johannesburg', 'cape town', 'durban', 'pretoria'],
          whole_word_keywords: [],
          activates: 'ZA'
        },
        {
          country: 'DE',
          regex: '\\b[1-9]\\d{10}\\b',
          flags: '',
          keywords: ['steuer', 'steuernummer', 'finanzamt', 'tax id', 'german'],
          whole_word_keywords: [],
          activates: 'DE'
        },
        {
          country: 'DE',
          regex: '\\b(\\+49|0049)\\d{10,11}\\b',
          flags: '',
          keywords: ['germany', 'german', 'deutschland', 'de'],
          whole_word_keywords: [],
          activates: 'DE'
        },
        {
          country: 'NG',
          regex: '\\b\\d{11}\\b',
          flags: '',
          keywords: ['bvn', 'nin', 'bank verification', 'nigeria', 'nigerian'],
          whole_word_keywords: [],
          activates: 'NG'
        },
        {
          country: 'NG',
          regex: '\\b(\\+234|0)[7-9]\\d{9}\\b',
          flags: '',
          keywords: ['nigeria', 'nigerian', 'lagos', 'abuja'],
          whole_word_keywords: [],
          activates: 'NG'
        },
        {
          country: 'AE',
          regex: '\\b784[- \\t]\\d{4}[- \\t]\\d{7}[- \\t]\\d{1}\\b',
          flags: '',
          keywords: [],
          whole_word_keywords: [],
          activates: 'AE'
        },
        {
          country: 'AE',
          regex: '\\b(\\+971|00971)\\d{9}\\b',
          flags: '',
          keywords: ['uae', 'emirates', 'dubai', 'abu dhabi'],
          whole_word_keywords: [],
          activates: 'AE'
        },
        {
          country: 'IN',
          regex: '\\b[A-Z]{5}\\d{4}[A-Z]{1}\\b',
          flags: '',
          keywords: [],
          whole_word_keywords: [],
          activates: 'IN'
        },
        {
          country: 'IN',
          regex: '\\b\\d{4}\\s\\d{4}\\s\\d{4}\\b',
          flags: '',
          keywords: ['aadhaar', 'aadhar', 'india', 'indian'],
          whole_word_keywords: [],
          activates: 'IN'
        },
        {
          country: 'SA',
          regex: '\\b1\\d{9}\\b',
          flags: '',
          keywords: ['saudi', 'ksa', 'riyadh', 'national id', 'iqama'],
          whole_word_keywords: [],
          activates: 'SA'
        },
        {
          country: 'SA',
          regex: '\\b(\\+966|00966)\\d{9}\\b',
          flags: '',
          keywords: ['saudi', 'ksa', 'riyadh'],
          whole_word_keywords: [],
          activates: 'SA'
        },
        {
          country: 'BR',
          regex: '\\b\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}\\b',
          flags: '',
          keywords: ['cpf', 'brazil', 'brasil', 'brazilian'],
          whole_word_keywords: [],
          activates: 'BR'
        },
        {
          country: 'BR',
          regex: '\\b(\\+55|0055)\\d{11}\\b',
          flags: '',
          keywords: ['brazil', 'brasil'],
          whole_word_keywords: [],
          activates: 'BR'
        },
        {
          country: 'JP',
          regex: '\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b',
          flags: '',
          keywords: ['my number', 'individual number', 'マイナンバー', '個人番号', 'japan', 'japanese', '日本', 'tokyo', 'osaka', 'nagoya', 'yokohama'],
          whole_word_keywords: [],
          activates: 'JP'
        },
        {
          country: 'JP',
          regex: '\\b(\\+81|0081)[ \\t]?\\d{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b',
          flags: '',
          keywords: ['japan', 'japanese', '日本', 'tokyo', 'osaka'],
          whole_word_keywords: [],
          activates: 'JP'
        },
        {
          country: 'CN',
          regex: '\\b\\d{17}[0-9Xx]\\b',
          flags: '',
          keywords: ['resident id', 'resident identity', 'identity card', 'id card', '身份证', '身份證', '居民身份证', 'china', 'chinese', 'prc', 'beijing', 'shanghai', 'shenzhen', 'guangzhou'],
          whole_word_keywords: [],
          activates: 'CN'
        },
        {
          country: 'CN',
          regex: '\\b(\\+86|0086)[ \\t]?1[3-9]\\d{9}\\b',
          flags: '',
          keywords: ['china', 'chinese', 'prc', 'beijing', 'shanghai', 'shenzhen', 'guangzhou'],
          whole_word_keywords: [],
          activates: 'CN'
        },
        {
          country: 'KR',
          regex: '\\b\\d{6}-?[1-8]\\d{6}\\b',
          flags: '',
          keywords: ['resident registration', 'resident number', 'rrn', 'jumin', '주민등록번호', '주민번호', 'korea', 'korean', 'seoul', 'busan', 'incheon'],
          whole_word_keywords: [],
          activates: 'KR'
        },
        {
          country: 'KR',
          regex: '\\b(\\+82|0082)[ \\t]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b',
          flags: '',
          keywords: ['korea', 'korean', 'seoul', 'busan', 'incheon'],
          whole_word_keywords: [],
          activates: 'KR'
        },
        {
          country: 'GH',
          regex: '\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b',
          flags: '',
          keywords: ['ghana card', 'ghanacard', 'ghana', 'accra', 'kumasi', 'nia pin', 'gra tin'],
          whole_word_keywords: [],
          activates: 'GH'
        },
        {
          country: 'GH',
          regex: '\\b(\\+233|00233)[ \\t]?\\d{9}\\b',
          flags: '',
          keywords: ['ghana', 'ghanaian', 'accra', 'kumasi', 'tema'],
          whole_word_keywords: [],
          activates: 'GH'
        },
        {
          country: 'IT',
          regex: '\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b',
          flags: '',
          keywords: ['codice fiscale', 'cod. fisc', 'c.f.', 'anagrafe tributaria', 'italy', 'italia', 'italian', 'italiana', 'roma', 'milano', 'napoli', 'torino'],
          whole_word_keywords: [],
          activates: 'IT'
        },
        {
          country: 'IT',
          regex: '\\b(\\+39|0039)[ \\t]?\\d{9,11}\\b',
          flags: '',
          keywords: ['italy', 'italia', 'italian', 'italiana', 'roma', 'milano', 'napoli', 'torino'],
          whole_word_keywords: [],
          activates: 'IT'
        },
        {
          country: 'KE',
          regex: '\\b[AP]\\d{9}[A-Z]\\b',
          flags: '',
          keywords: ['kra', 'itax', 'tax pin', 'kenya', 'kenyan', 'nairobi', 'mombasa', 'kisumu'],
          whole_word_keywords: [],
          activates: 'KE'
        },
        {
          country: 'KE',
          regex: '\\b(\\+254|00254)[ \\t]?\\d{9}\\b',
          flags: '',
          keywords: ['kenya', 'kenyan', 'nairobi', 'mombasa', 'kisumu'],
          whole_word_keywords: [],
          activates: 'KE'
        },
        {
          country: 'MU',
          regex: '\\b[123578]\\d{7}\\b',
          flags: '',
          keywords: ['mauritius', 'mauritian', 'port louis', 'mauritius revenue', 'mra tan'],
          whole_word_keywords: [],
          activates: 'MU'
        },
        {
          country: 'MU',
          regex: '\\b(\\+230|00230)[ \\t]?\\d{7,8}\\b',
          flags: '',
          keywords: ['mauritius', 'mauritian', 'port louis'],
          whole_word_keywords: [],
          activates: 'MU'
        },
        {
          country: 'MX',
          regex: '\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b',
          flags: '',
          keywords: ['rfc', 'homoclave', 'contribuyentes', 'mexico', 'méxico', 'mexican', 'mexicano', 'cdmx', 'guadalajara', 'monterrey'],
          whole_word_keywords: [],
          activates: 'MX'
        },
        {
          country: 'MX',
          regex: '\\b(\\+52|0052)[ \\t]?\\d{10}\\b',
          flags: '',
          keywords: ['mexico', 'méxico', 'mexican', 'mexicano', 'cdmx', 'guadalajara', 'monterrey'],
          whole_word_keywords: [],
          activates: 'MX'
        },
        {
          country: 'MY',
          regex: '\\b\\d{6}-\\d{2}-\\d{4}\\b',
          flags: '',
          keywords: ['mykad', 'kad pengenalan', 'nric', 'malaysia', 'malaysian', 'kuala lumpur', 'johor', 'penang', 'putrajaya', 'selangor'],
          whole_word_keywords: [],
          activates: 'MY'
        },
        {
          country: 'MY',
          regex: '\\b\\d{12}\\b',
          flags: '',
          keywords: ['mykad', 'my kad', 'kad pengenalan', 'mykid'],
          whole_word_keywords: [],
          activates: 'MY'
        },
        {
          country: 'MY',
          regex: '\\b(\\+60|0060)[ \\t]?\\d{9,10}\\b',
          flags: '',
          keywords: ['malaysia', 'malaysian', 'kuala lumpur', 'johor', 'penang'],
          whole_word_keywords: [],
          activates: 'MY'
        },
        {
          country: 'PK',
          regex: '\\b\\d{5}-\\d{7}-\\d\\b',
          flags: '',
          keywords: ['cnic', 'nadra', 'pakistan', 'pakistani', 'karachi', 'lahore', 'islamabad', 'rawalpindi', 'شناختی'],
          whole_word_keywords: [],
          activates: 'PK'
        },
        {
          country: 'PK',
          regex: '\\b\\d{13}\\b',
          flags: '',
          keywords: ['cnic', 'nadra', 'شناختی'],
          whole_word_keywords: [],
          activates: 'PK'
        },
        {
          country: 'PK',
          regex: '\\b(\\+92|0092)[ \\t]?3\\d{9}\\b',
          flags: '',
          keywords: ['pakistan', 'pakistani', 'karachi', 'lahore', 'islamabad'],
          whole_word_keywords: [],
          activates: 'PK'
        },
        {
          country: 'SG',
          regex: '\\b[STFGM]\\d{7}[A-Z]\\b',
          flags: '',
          keywords: ['nric', 'singpass', 'cpf', 'iras', 'singapore', 'singaporean'],
          whole_word_keywords: [],
          activates: 'SG'
        },
        {
          country: 'SG',
          regex: '\\b(\\+65|0065)[ \\t]?[689]\\d{3}[ \\t]?\\d{4}\\b',
          flags: '',
          keywords: ['singapore', 'singaporean'],
          whole_word_keywords: [],
          activates: 'SG'
        },
        {
          country: 'TH',
          regex: '\\b\\d-\\d{4}-\\d{5}-\\d{2}-\\d\\b',
          flags: '',
          keywords: ['national id', 'thai', 'thailand', 'เลขประจำตัวประชาชน', 'บัตรประชาชน', 'bangkok', 'promptpay'],
          whole_word_keywords: [],
          activates: 'TH'
        },
        {
          country: 'TH',
          regex: '\\b\\d{13}\\b',
          flags: '',
          keywords: ['thai id', 'thailand', 'เลขประจำตัวประชาชน', 'บัตรประชาชน', 'promptpay'],
          whole_word_keywords: [],
          activates: 'TH'
        },
        {
          country: 'TH',
          regex: '\\b(\\+66|0066)[ \\t]?\\d{9}\\b',
          flags: '',
          keywords: ['thailand', 'thai', 'bangkok', 'phuket', 'chiang mai'],
          whole_word_keywords: [],
          activates: 'TH'
        },
        {
          country: 'ID',
          regex: '\\b\\d{16}\\b',
          flags: '',
          keywords: ['nomor induk kependudukan', 'kartu tanda penduduk', 'dukcapil'],
          whole_word_keywords: ['nik', 'e-ktp', 'ektp', 'ktp', 'npwp'],
          activates: 'ID'
        },
        {
          country: 'ID',
          regex: '\\b(\\+62|0062)[ \\t]?\\d{9,12}\\b',
          flags: '',
          keywords: ['indonesia', 'indonesian', 'jakarta', 'surabaya', 'bandung', 'medan', 'bali'],
          whole_word_keywords: [],
          activates: 'ID'
        },
      ].freeze
    end
  end
end
